// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rflwipjlcbryzqmkxriv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbHdpcGpsY2JyeXpxbWt4cml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODMyNjAsImV4cCI6MjA2NjY1OTI2MH0.ehkzEDe1YdHBsiXg1UOnV-3rRRIa-chqLZ97FM_8AeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);